// <auto-generated />
using System;
using AgroNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AgroNet.Models.Cosecha", b =>
                {
                    b.Property<int>("CosechaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CosechaId"));

                    b.Property<decimal>("CantidadDisponible")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaEstimada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdFinca")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioPorUnidad")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CosechaId");

                    b.HasIndex("IdFinca");

                    b.HasIndex("IdProducto");

                    b.ToTable("Cosechas");
                });

            modelBuilder.Entity("AgroNet.Models.DetallePedido", b =>
                {
                    b.Property<int>("DetallePedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetallePedidoId"));

                    b.Property<decimal>("CantidadComprada")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IdCosecha")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DetallePedidoId");

                    b.HasIndex("IdCosecha");

                    b.HasIndex("IdPedido");

                    b.ToTable("DetallePedidos");
                });

            modelBuilder.Entity("AgroNet.Models.Finca", b =>
                {
                    b.Property<int>("FincaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FincaId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreFinca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FincaId");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Fincas");
                });

            modelBuilder.Entity("AgroNet.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<string>("EstadoPedido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPagar")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("PedidoId");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("AgroNet.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("AgroNet.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AgroNet.Models.Trazabilidad", b =>
                {
                    b.Property<int>("TrazabilidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TrazabilidadId"));

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCosecha")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TrazabilidadId");

                    b.HasIndex("IdCosecha");

                    b.ToTable("Trazabilidad");
                });

            modelBuilder.Entity("AgroNet.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AgroNet.Models.Cosecha", b =>
                {
                    b.HasOne("AgroNet.Models.Finca", "Finca")
                        .WithMany("Cosechas")
                        .HasForeignKey("IdFinca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroNet.Models.Producto", "Producto")
                        .WithMany("Cosechas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AgroNet.Models.DetallePedido", b =>
                {
                    b.HasOne("AgroNet.Models.Cosecha", "Cosecha")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdCosecha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroNet.Models.Pedido", "Pedido")
                        .WithMany("DetallePedidos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cosecha");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("AgroNet.Models.Finca", b =>
                {
                    b.HasOne("AgroNet.Models.Usuario", "Usuario")
                        .WithMany("Fincas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgroNet.Models.Pedido", b =>
                {
                    b.HasOne("AgroNet.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgroNet.Models.Trazabilidad", b =>
                {
                    b.HasOne("AgroNet.Models.Cosecha", "Cosecha")
                        .WithMany("Trazabilidades")
                        .HasForeignKey("IdCosecha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cosecha");
                });

            modelBuilder.Entity("AgroNet.Models.Usuario", b =>
                {
                    b.HasOne("AgroNet.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AgroNet.Models.Cosecha", b =>
                {
                    b.Navigation("DetallePedidos");

                    b.Navigation("Trazabilidades");
                });

            modelBuilder.Entity("AgroNet.Models.Finca", b =>
                {
                    b.Navigation("Cosechas");
                });

            modelBuilder.Entity("AgroNet.Models.Pedido", b =>
                {
                    b.Navigation("DetallePedidos");
                });

            modelBuilder.Entity("AgroNet.Models.Producto", b =>
                {
                    b.Navigation("Cosechas");
                });

            modelBuilder.Entity("AgroNet.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AgroNet.Models.Usuario", b =>
                {
                    b.Navigation("Fincas");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
